apiVersion: v1
kind: Pod
metadata:
  name: mistletoe-01-group-01--0
spec:
  containers:
    - name: nginx
      image: nginx:1.14.0
      imagePullPolicy: IfNotPresent
      ports:
      - name: http
        containerPort: 80
        hostPort: 8999

---
